### ISSUE TITLE
Crash when no "oauth_consumer_key" parameter

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#132]
If you post to the `/lti_launches` URL without an `"oauth_consumer_key"` param in the request it crashes.

For example simply making an empty `POST` request to <https://lms.hypothes.is/lti_launches> will crash the production app:

```
$ http POST 'https://lms.hypothes.is/lti_launches'
HTTP/1.1 500 Internal Server Error
CF-RAY: 43eff4d3de34bfe5-MAN
Connection: keep-alive
Content-Length: 141
Content-Type: text/html
Date: Mon, 23 Jul 2018 17:44:40 GMT
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
Set-Cookie: __cfduid=ddb7634f46322be02ffe9025535c7630f1532367880; expires=Tue, 23-Jul-19 17:44:40 GMT; path=/; domain=.hypothes.is; HttpOnly
Strict-Transport-Security: max-age=15552000; includeSubDomains; preload
X-Content-Type-Options: nosniff

<html>
  <head>
    <title>Internal Server Error</title>
  </head>
  <body>
    <h1><p>Internal Server Error</p></h1>
    
  </body>
</html>
```

Traceback:

```
Traceback (most recent call last):
  File "/home/seanh/.virtualenvs/lms/lib/python3.6/site-packages/pyramid_debugtoolbar/toolbar.py", line 248, in toolbar_tween
    response = _handler(request)
  File "/home/seanh/.virtualenvs/lms/lib/python3.6/site-packages/pyramid_debugtoolbar/panels/performance.py", line 58, in resource_timer_handler
    result = handler(request)
  File "/home/seanh/.virtualenvs/lms/lib/python3.6/site-packages/pyramid_tm/__init__.py", line 171, in tm_tween
    reraise(*exc_info)
  File "/home/seanh/.virtualenvs/lms/lib/python3.6/site-packages/pyramid_tm/compat.py", line 36, in reraise
    raise value
  File "/home/seanh/.virtualenvs/lms/lib/python3.6/site-packages/pyramid_tm/__init__.py", line 136, in tm_tween
    response = handler(request)
  File "/home/seanh/.virtualenvs/lms/lib/python3.6/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = _error_handler(request, exc)
  File "/home/seanh/.virtualenvs/lms/lib/python3.6/site-packages/pyramid/tweens.py", line 16, in _error_handler
    reraise(*exc_info)
  File "/home/seanh/.virtualenvs/lms/lib/python3.6/site-packages/pyramid/compat.py", line 148, in reraise
    raise value
  File "/home/seanh/.virtualenvs/lms/lib/python3.6/site-packages/pyramid/tweens.py", line 39, in excview_tween
    response = handler(request)
  File "/home/seanh/.virtualenvs/lms/lib/python3.6/site-packages/pyramid/router.py", line 156, in handle_request
    view_name
  File "/home/seanh/.virtualenvs/lms/lib/python3.6/site-packages/pyramid/view.py", line 642, in _call_view
    response = view_callable(context, request)
  File "/home/seanh/.virtualenvs/lms/lib/python3.6/site-packages/pyramid/viewderivers.py", line 390, in attr_view
    return view(context, request)
  File "/home/seanh/.virtualenvs/lms/lib/python3.6/site-packages/pyramid/viewderivers.py", line 368, in predicate_wrapper
    return view(context, request)
  File "/home/seanh/.virtualenvs/lms/lib/python3.6/site-packages/pyramid/viewderivers.py", line 410, in viewresult_to_response
    result = view(context, request)
  File "/home/seanh/.virtualenvs/lms/lib/python3.6/site-packages/pyramid/viewderivers.py", line 148, in _requestonly_view
    response = view(request)
  File "/home/seanh/Projects/lms/lms/util/lti_launch.py", line 49, in wrapper
    consumer_key = lti_params['oauth_consumer_key']
KeyError: 'oauth_consumer_key'
```

**Comment by seanh** [comment]
Sentry issue: [LMS-BACKEND-P](https://sentry.io/hypothesis/lms-backend/issues/474727106/)
