### ISSUE TITLE
Crash when oauth_consumer_key invalid

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#133]
If you post to the `/lti_launches` URL with an invalid `"oauth_consumer_key"` param in the request it crashes.

For example simply making a `POST` request to <https://lms.hypothes.is/lti_launches> with a random `"oauth_consumer_key"` in the request body will crash the production app:

```
$ http --form POST 'https://lms.hypothes.is/lti_launches' oauth_consumer_key=foo
HTTP/1.1 500 Internal Server Error
CF-RAY: 43f0123a1ad2364d-MAN
Connection: keep-alive
Content-Length: 141
Content-Type: text/html
Date: Mon, 23 Jul 2018 18:04:45 GMT
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
Set-Cookie: __cfduid=d701463e08bd827f0579a12eae43e3d741532369084; expires=Tue, 23-Jul-19 18:04:44 GMT; path=/; domain=.hypothes.is; HttpOnly
Strict-Transport-Security: max-age=15552000; includeSubDomains; preload
X-Content-Type-Options: nosniff

<html>
  <head>
    <title>Internal Server Error</title>
  </head>
  <body>
    <h1><p>Internal Server Error</p></h1>
    
  </body>
</html>

```

Related:

* https://github.com/hypothesis/lms/issues/132

Traceback:

```
Traceback (most recent call last):
  File "/home/seanh/.virtualenvs/lms/lib/python3.6/site-packages/pyramid_debugtoolbar/toolbar.py", line 248, in toolbar_tween
    response = _handler(request)
  File "/home/seanh/.virtualenvs/lms/lib/python3.6/site-packages/pyramid_debugtoolbar/panels/performance.py", line 58, in resource_timer_handler
    result = handler(request)
  File "/home/seanh/.virtualenvs/lms/lib/python3.6/site-packages/pyramid_tm/__init__.py", line 171, in tm_tween
    reraise(*exc_info)
  File "/home/seanh/.virtualenvs/lms/lib/python3.6/site-packages/pyramid_tm/compat.py", line 36, in reraise
    raise value
  File "/home/seanh/.virtualenvs/lms/lib/python3.6/site-packages/pyramid_tm/__init__.py", line 136, in tm_tween
    response = handler(request)
  File "/home/seanh/.virtualenvs/lms/lib/python3.6/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = _error_handler(request, exc)
  File "/home/seanh/.virtualenvs/lms/lib/python3.6/site-packages/pyramid/tweens.py", line 16, in _error_handler
    reraise(*exc_info)
  File "/home/seanh/.virtualenvs/lms/lib/python3.6/site-packages/pyramid/compat.py", line 148, in reraise
    raise value
  File "/home/seanh/.virtualenvs/lms/lib/python3.6/site-packages/pyramid/tweens.py", line 39, in excview_tween
    response = handler(request)
  File "/home/seanh/.virtualenvs/lms/lib/python3.6/site-packages/pyramid/router.py", line 156, in handle_request
    view_name
  File "/home/seanh/.virtualenvs/lms/lib/python3.6/site-packages/pyramid/view.py", line 642, in _call_view
    response = view_callable(context, request)
  File "/home/seanh/.virtualenvs/lms/lib/python3.6/site-packages/pyramid/viewderivers.py", line 390, in attr_view
    return view(context, request)
  File "/home/seanh/.virtualenvs/lms/lib/python3.6/site-packages/pyramid/viewderivers.py", line 368, in predicate_wrapper
    return view(context, request)
  File "/home/seanh/.virtualenvs/lms/lib/python3.6/site-packages/pyramid/viewderivers.py", line 410, in viewresult_to_response
    result = view(context, request)
  File "/home/seanh/.virtualenvs/lms/lib/python3.6/site-packages/pyramid/viewderivers.py", line 148, in _requestonly_view
    response = view(request)
  File "/home/seanh/Projects/lms/lms/util/lti_launch.py", line 50, in wrapper
    shared_secret = get_secret(request, consumer_key)
  File "/home/seanh/Projects/lms/lms/util/lti_launch.py", line 16, in default_get_secret
    instance = get_application_instance(request.db, consumer_key)
  File "/home/seanh/Projects/lms/lms/util/lti_launch.py", line 10, in get_application_instance
    ai.ApplicationInstance.consumer_key == consumer_key
  File "/home/seanh/.virtualenvs/lms/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2820, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()```

**Comment by seanh** [comment]
Sentry issue: [LMS-BACKEND-E](https://sentry.io/hypothesis/lms-backend/issues/432668851/)

**Comment by robertknight** [comment]
I encountered this when I'd entered the wrong value into the consume key field when adding my local Hypothesis LMS app instance to https://hypothesis.instructure.com and then tried to configure Hypothesis for a new assignment which performs a `POST /content_item_selection` request to the lms app.

**Comment by seanh** [comment]
Sentry issue: [LMS-BACKEND-1Y](https://sentry.io/hypothesis/lms-backend/issues/780711343/?referrer=github_plugin)

**Comment by seanh** [comment]
I'm gonna assume this is now fixed, unless it reoccurs
